spring.application.name=api
spring.datasource.url=${URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
server.port=${PORT}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.web.error.include-stacktrace=never
api.security.token.secret=${JWT_SECRET:12345678}