spring.application.name=api
spring.datasource.url=${URL:jdbc:mysql://localhost:3306/vollmed_api}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
server.port=${PORT:8080}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.web.error.include-stacktrace=never
api.security.token.secret=${JWT_SECRET:12345678}